language: php

php:
    - 5.6
    - 7.0
    - 7.1

matrix:
  fast_finish: true
  allow_failures:
      - php: 5.6

before_script:
    - travis_retry composer self-update
    - travis_retry composer global require hirak/prestissimo
    - travis_retry composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

notifications:
    script:
        - "phpunit -v --coverage-text --colors=never --stderr"

after_success:
    - php vendor/bin/codacycoverage clover path/to/clover.xml

addons:
    code_climate:
        repo_token: 63cc3eed8d525282d388e78d015f4cb91b1875f0c971d72e105fbe8a7bf0e798